// examples/react/VideoConference.tsx
import React, { useCallback, useState } from 'react';
import { useWebRTC } from 'webrtc-easy/react';
import { WebSocketSignaling } from 'webrtc-easy/core';

const VideoConference: React.FC = () => {
  const [signaling, setSignaling] = useState<WebSocketSignaling | null>(null);
  const { 
    localStream, 
    remoteStream, 
    connection,
    connectionState,
    error,
    initConnection, 
    startScreenShare 
  } = useWebRTC({
    configuration: {
      iceServers: [{ urls: 'stun:stun.l.google.com:19302' }]
    }
  });

  const handleStart = async () => {
    try {
      const conn = await initConnection();
      
      const ws = new WebSocketSignaling({
        url: 'wss://your-signaling-server.com',
        room: 'test-room',
        autoReconnect: true
      });

      ws.onMessage(async (message) => {
        switch (message.type) {
          case 'offer':
            const answer = await conn.createAnswer(message.payload);
            ws.send({ type: 'answer', payload: answer });
            break;
          case 'answer':
            await conn.handleAnswer(message.payload);
            break;
          case 'ice-candidate':
            await conn.addIceCandidate(message.payload);
            break;
        }
      });

      setSignaling(ws);

      // Create and send offer
      const offer = await conn.createOffer();
      ws.send({ type: 'offer', payload: offer });
    } catch (err) {
      console.error('Failed to start call:', err);
    }
  };

  const handleScreenShare = async () => {
    try {
      await startScreenShare();
    } catch (err) {
      console.error('Failed to share screen:', err);
    }
  };

  const handleDisconnect = useCallback(() => {
    signaling?.disconnect();
    setSignaling(null);
  }, [signaling]);

  return (
    <div className="video-conference">
      <div className="controls">
        <button 
          onClick={handleStart}
          disabled={!!signaling}
        >
          Start Call
        </button>
        <button 
          onClick={handleScreenShare}
          disabled={!signaling}
        >
          Share Screen
        </button>
        <button 
          onClick={handleDisconnect}
          disabled={!signaling}
        >
          End Call
        </button>
      </div>

      {error && (
        <div className="error-message">
          Error: {error.message}
        </div>
      )}

      <div className="connection-status">
        Connection: {connectionState}
      </div>

      <div className="video-streams">
        <div className="local-stream">
          <h3>Local Stream</h3>
          {localStream && (
            <video
              autoPlay
              playsInline
              muted
              ref={video => {
                if (video) video.srcObject = localStream;
              }}
            />
          )}
        </div>

        <div className="remote-stream">
          <h3>Remote Stream</h3>
          {remoteStream && (
            <video
              autoPlay
              playsInline
              ref={video => {
                if (video) video.srcObject = remoteStream;
              }}
            />
          )}
        </div>
      </div>
    </div>
  );
};

export default VideoConference;

// examples/angular/video-conference/video-conference.component.ts
import { Component, ElementRef, OnDestroy, ViewChild } from '@angular/core';
import { WebRTCService } from 'webrtc-easy/angular';
import { WebSocketSignaling } from 'webrtc-easy/core';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-video-conference',
  template: `
    <div class="video-conference">
      <div class="controls">
        <button 
          (click)="handleStart()"
          [disabled]="!!signaling"
        >
          Start Call
        </button>
        <button 
          (click)="handleScreenShare()"
          [disabled]="!signaling"
        >
          Share Screen
        </button>
        <button 
          (click)="handleDisconnect()"
          [disabled]="!signaling"
        >
          End Call
        </button>
      </div>

      <div *ngIf="error$ | async as error" class="error-message">
        Error: {{ error.message }}
      </div>

      <div class="connection-status">
        Connection: {{ connectionState$ | async }}
      </div>

      <div class="video-streams">
        <div class="local-stream">
          <h3>Local Stream</h3>
          <video #localVideo autoplay playsinline muted></video>
        </div>
        <div class="remote-stream">
          <h3>Remote Stream</h3>
          <video #remoteVideo autoplay playsinline></video>
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./video-conference.component.scss']
})
export class VideoConferenceComponent implements OnDestroy {
  @ViewChild('localVideo') localVideo!: ElementRef<HTMLVideoElement>;
  @ViewChild('remoteVideo') remoteVideo!: ElementRef<HTMLVideoElement>;

  private signaling: WebSocketSignaling | null = null;
  private subscriptions: Subscription[] = [];

  constructor(private webRTCService: WebRTCService) {
    this.setupStreamSubscriptions();
  }

  private setupStreamSubscriptions(): void {
    this.subscriptions.push(
      this.webRTCService.localStream$.subscribe(stream => {
        if (this.localVideo?.nativeElement && stream) {
          this.localVideo.nativeElement.srcObject = stream;
        }
      }),

      this.webRTCService.remoteStream$.subscribe(stream => {
        if (this.remoteVideo?.nativeElement && stream) {
          this.remoteVideo.nativeElement.srcObject = stream;
        }
      })
    );
  }

  async handleStart(): Promise<void> {
    try {
      const conn = await this.webRTCService.initConnection();
      
      this.signaling = new WebSocketSignaling({
        url: 'wss://your-signaling-server.com',
        room: 'test-room',
        autoReconnect: true
      });

      this.signaling.onMessage(async (message) => {
        switch (message.type) {
          case 'offer':
            const answer = await conn.createAnswer(message.payload);
            this.signaling?.send({ type: 'answer', payload: answer });
            break;
          case 'answer':
            await conn.handleAnswer(message.payload);
            break;
          case 'ice-candidate':
            await conn.addIceCandidate(message.payload);
            break;
        }
      });

      const offer = await conn.createOffer();
      this.signaling.send({ type: 'offer', payload: offer });
    } catch (err) {
      console.error('Failed to start call:', err);
    }
  }

  async handleScreenShare(): Promise<void> {
    try {
      await this.webRTCService.startScreenShare();
    } catch (err) {
      console.error('Failed to share screen:', err);
    }
  }

  handleDisconnect(): void {
    this.signaling?.disconnect();
    this.signaling = null;
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach(sub => sub.unsubscribe());
    this.handleDisconnect();
  }

  get error$() { return this.webRTCService.error$; }
  get connectionState$() { return this.webRTCService.connectionState$; }
}
